"""
Unit tests: Prescription PDF generation and WhatsApp delivery.

Verifies:
- generate_prescription_pdf() produces non-empty PDF bytes containing
  clinic, patient, doctor, and medications fields
- send_prescription_pdf() uploads to Meta API, sends WhatsApp document,
  and falls back to text on failure
- POST /prescription/send returns HTTP 200 on success and HTTP 502 on failure

Task 6.4 — Validates: Requirements 8.1, 8.2, 8.3, 8.4, 8.5
"""
import asyncio
import io
import os
import zlib
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from starlette.testclient import TestClient


# ---------------------------------------------------------------------------
# Async helper
# ---------------------------------------------------------------------------

def run_async(coro):
    loop = asyncio.new_event_loop()
    try:
        return loop.run_until_complete(coro)
    finally:
        loop.close()


# ---------------------------------------------------------------------------
# PDF text extraction helper
# ReportLab uses ASCII85Decode + FlateDecode (two-filter chain) on content
# streams. We patch reportlab's global compress flag to disable compression
# so the content stream is readable for text assertions.
# ---------------------------------------------------------------------------

def generate_uncompressed_pdf(**kwargs) -> bytes:
    """
    Generate a prescription PDF with compression disabled.

    Patches reportlab.rl_config.pageCompression and useA85 so the content
    stream is written as plain uncompressed text, making it searchable in
    the raw bytes for assertion purposes.
    """
    import reportlab.rl_config as _rl_config
    orig_page_compression = _rl_config.pageCompression
    orig_use_a85 = _rl_config.useA85
    _rl_config.pageCompression = 0
    _rl_config.useA85 = 0
    try:
        from app.pdf_service import generate_prescription_pdf
        return generate_prescription_pdf(**kwargs)
    finally:
        _rl_config.pageCompression = orig_page_compression
        _rl_config.useA85 = orig_use_a85


# ---------------------------------------------------------------------------
# 6.4.1 — generate_prescription_pdf() produces non-empty PDF bytes
# ---------------------------------------------------------------------------

def test_generate_prescription_pdf_returns_bytes():
    """
    generate_prescription_pdf() must return non-empty bytes.
    Validates: Requirements 8.1
    """
    from app.pdf_service import generate_prescription_pdf

    pdf_bytes = generate_prescription_pdf(
        patient_name="Ravi Kumar",
        doctor_name="Dr. Sharma",
        medications=[
            {"name": "Paracetamol", "dose": "500mg", "frequency": "Twice daily", "duration": "5 days"}
        ],
        instructions="Take after meals.",
    )

    assert isinstance(pdf_bytes, bytes), "PDF output must be bytes"
    assert len(pdf_bytes) > 0, "PDF output must not be empty"


def test_generate_prescription_pdf_starts_with_pdf_header():
    """
    The generated bytes must start with the PDF magic bytes (%PDF-).
    Validates: Requirements 8.1
    """
    from app.pdf_service import generate_prescription_pdf

    pdf_bytes = generate_prescription_pdf(
        patient_name="Priya Singh",
        doctor_name="Dr. Mehta",
        medications=[],
        instructions="",
    )

    assert pdf_bytes[:4] == b"%PDF", (
        f"Expected PDF magic bytes '%PDF', got {pdf_bytes[:4]!r}"
    )


def test_generate_prescription_pdf_contains_patient_name():
    """
    The generated PDF must contain the patient name in its content stream.
    Validates: Requirements 8.1
    """
    patient_name = "Anita Desai"
    pdf_bytes = generate_uncompressed_pdf(
        patient_name=patient_name,
        doctor_name="Dr. Patel",
        medications=[],
        instructions="",
    )

    assert patient_name.encode("latin-1") in pdf_bytes, (
        f"Patient name '{patient_name}' not found in uncompressed PDF content"
    )


def test_generate_prescription_pdf_contains_doctor_name():
    """
    The generated PDF must contain the doctor name in its content stream.
    Validates: Requirements 8.1
    """
    doctor_name = "Dr. Kapoor"
    pdf_bytes = generate_uncompressed_pdf(
        patient_name="Test Patient",
        doctor_name=doctor_name,
        medications=[],
        instructions="",
    )

    assert doctor_name.encode("latin-1") in pdf_bytes, (
        f"Doctor name '{doctor_name}' not found in uncompressed PDF content"
    )


def test_generate_prescription_pdf_contains_clinic_name():
    """
    The generated PDF must contain the clinic name in its content stream.
    Validates: Requirements 8.1
    """
    clinic_name = "Sunrise Medical Centre"
    pdf_bytes = generate_uncompressed_pdf(
        patient_name="Test Patient",
        doctor_name="Dr. Test",
        medications=[],
        instructions="",
        clinic_name=clinic_name,
    )

    assert clinic_name.encode("latin-1") in pdf_bytes, (
        f"Clinic name '{clinic_name}' not found in uncompressed PDF content"
    )


def test_generate_prescription_pdf_contains_medication_name():
    """
    The generated PDF must contain medication names in its content stream.
    Validates: Requirements 8.1
    """
    med_name = "Amoxicillin"
    pdf_bytes = generate_uncompressed_pdf(
        patient_name="Test Patient",
        doctor_name="Dr. Test",
        medications=[
            {"name": med_name, "dose": "250mg", "frequency": "Three times daily", "duration": "7 days"}
        ],
        instructions="",
    )

    assert med_name.encode("latin-1") in pdf_bytes, (
        f"Medication name '{med_name}' not found in uncompressed PDF content"
    )


# ---------------------------------------------------------------------------
# 6.4.2 — send_prescription_pdf() uploads to Meta API and sends document
# ---------------------------------------------------------------------------

def test_send_prescription_pdf_calls_upload_and_send():
    """
    send_prescription_pdf() must call upload_whatsapp_media() and then
    send_whatsapp_document() on success.
    Validates: Requirements 8.2, 8.3
    """
    from app.main import send_prescription_pdf

    mock_media_id = "media_abc123"

    async def _run():
        with patch("app.main.upload_whatsapp_media", new=AsyncMock(return_value=mock_media_id)) as mock_upload:
            with patch("app.main.send_whatsapp_document", new=AsyncMock()) as mock_send_doc:
                with patch("app.main.send_whatsapp_text", new=AsyncMock()):
                    result = await send_prescription_pdf(
                        to_phone="919999999999",
                        patient_name="Ravi Kumar",
                        doctor_name="Dr. Sharma",
                        medications=[{"name": "Paracetamol", "dose": "500mg", "frequency": "Twice daily", "duration": "5 days"}],
                        instructions="Take after meals.",
                    )

        assert result is True, "send_prescription_pdf must return True on success"
        mock_upload.assert_called_once()
        mock_send_doc.assert_called_once()

        # Verify the document was sent to the correct phone
        call_kwargs = mock_send_doc.call_args
        assert call_kwargs.kwargs.get("to_phone") == "919999999999" or call_kwargs.args[0] == "919999999999"
        assert call_kwargs.kwargs.get("media_id") == mock_media_id or mock_media_id in call_kwargs.args

    run_async(_run())


def test_send_prescription_pdf_falls_back_to_text_on_upload_failure():
    """
    send_prescription_pdf() must send a fallback WhatsApp text message
    when the Meta API media upload fails.
    Validates: Requirements 8.5
    """
    from app.main import send_prescription_pdf

    fallback_messages = []

    async def mock_send_text(to_phone: str, text: str, **kwargs):
        fallback_messages.append({"to": to_phone, "text": text})

    async def _run():
        with patch("app.main.upload_whatsapp_media", new=AsyncMock(side_effect=RuntimeError("Upload failed"))):
            with patch("app.main.send_whatsapp_text", side_effect=mock_send_text):
                result = await send_prescription_pdf(
                    to_phone="919999999999",
                    patient_name="Ravi Kumar",
                    doctor_name="Dr. Sharma",
                    medications=[],
                    instructions="",
                )

        assert result is False, "send_prescription_pdf must return False on failure"
        assert len(fallback_messages) >= 1, "A fallback text message must be sent on failure"
        assert "919999999999" == fallback_messages[0]["to"]

    run_async(_run())


# ---------------------------------------------------------------------------
# 6.4.3 — POST /prescription/send returns HTTP 200 on success, 502 on failure
# ---------------------------------------------------------------------------

PRESCRIPTION_PAYLOAD = {
    "to_phone": "919999999999",
    "patient_name": "Ravi Kumar",
    "doctor_name": "Dr. Sharma",
    "medications": [
        {"name": "Paracetamol", "dose": "500mg", "frequency": "Twice daily", "duration": "5 days"}
    ],
    "instructions": "Take after meals.",
}

ENV_PATCH = {
    "DATABASE_URL": "sqlite+aiosqlite:///:memory:",
    "META_PHONE_ID": "test_phone_id",
    "META_ACCESS_TOKEN": "test_access_token",
}


def test_prescription_endpoint_returns_200_on_success():
    """
    POST /prescription/send must return HTTP 200 when PDF delivery succeeds.
    Validates: Requirements 8.4
    """
    with patch.dict(os.environ, ENV_PATCH):
        with patch("app.main.start_scheduler"):
            with patch("app.main.stop_scheduler"):
                with patch("app.main.send_prescription_pdf", new=AsyncMock(return_value=True)):
                    from app.main import app as fastapi_app

                    with TestClient(fastapi_app) as client:
                        response = client.post("/prescription/send", json=PRESCRIPTION_PAYLOAD)

    assert response.status_code == 200, (
        f"Expected HTTP 200, got {response.status_code}: {response.text}"
    )
    body = response.json()
    assert body.get("status") == "success"


def test_prescription_endpoint_returns_502_on_failure():
    """
    POST /prescription/send must return HTTP 502 when PDF delivery fails.
    Validates: Requirements 8.5
    """
    with patch.dict(os.environ, ENV_PATCH):
        with patch("app.main.start_scheduler"):
            with patch("app.main.stop_scheduler"):
                with patch("app.main.send_prescription_pdf", new=AsyncMock(return_value=False)):
                    from app.main import app as fastapi_app

                    with TestClient(fastapi_app) as client:
                        response = client.post("/prescription/send", json=PRESCRIPTION_PAYLOAD)

    assert response.status_code == 502, (
        f"Expected HTTP 502, got {response.status_code}: {response.text}"
    )
    body = response.json()
    assert "detail" in body
